HOST = "0.0.0.0"
PORT = 8080

CHRONY_TRACKING_INTERVAL = 1.0
CHRONY_SOURCES_INTERVAL = 5.0
CHRONY_SERVERSTATS_INTERVAL = 10.0
CHRONY_CLIENTS_INTERVAL = 30.0
PTP_INTERVAL = 2.0
PPS_INTERVAL = 1.0
SYSTEMD_INTERVAL = 5.0

GPSD_HOST = "127.0.0.1"
GPSD_PORT = 2947

PTP4L_RO_SOCKET = "/var/run/ptp4lro"
PPS_DEVICES = ["/sys/class/pps/pps0/assert", "/sys/class/pps/pps1/assert"]

RING_SECONDS = 3600
SERVICES = ["chrony", "gpsd", "ptp4l", "phc2sys"]
SSE_PUSH_INTERVAL = 1.0
